// Generated by scripts/generate-funnel-catalog.mjs. Do not edit by hand.
export const FUNNELS = [
  {
    offerSlug: 'owned-funnel-builder',
    supportEmail: 'support@example.com',
    base: {
      productKey: 'owned-funnel-builder',
      name: 'Owned Funnel Builder',
      priceAmount: 49,
      currency: 'USD',
      deliverySubject: 'Your Owned Funnel Builder access',
      deliveryBody:
        'Thanks for your purchase. Your builder, zero-skill quickstart, and setup instructions are ready at the link below.',
      accessUrl: 'https://example.com/replace-with-your-access-link',
    },
    bump: {
      key: 'conversion-copy-swipe-file',
      productKey: 'owned-funnel-conversion-copy-swipe-file',
      name: 'Conversion Copy Swipe File',
      priceAmount: 19,
      currency: 'USD',
      deliverySubject: 'Your Conversion Copy Swipe File',
      deliveryBody:
        'Your headline starters, section prompts, objection answers, and guarantee swipe copy are ready at the link below.',
      accessUrl: 'https://example.com/replace-with-your-access-link',
    },
    upsells: [
      {
        key: 'funnel-blueprints',
        productKey: 'owned-funnel-ten-blueprints',
        name: 'Ten-Funnel Blueprint Pack',
        stepLabel: 'Upgrade 1 of 2',
        eyebrow: 'Skip the offer-planning blank page',
        title: 'Want ten proven funnel structures',
        accent: 'ready to adapt?',
        description:
          'Give your agent a concrete starting brief for the most common low-ticket and service offers instead of inventing the structure from scratch.',
        price: '$39',
        regularPrice: '$99',
        priceAmount: 39,
        currency: 'USD',
        items: [
          'Digital guide and template funnel',
          'Workshop and course-recording funnel',
          'Paid diagnostic funnel',
          'Consulting and productized-service funnel',
          'Waitlist and presale funnel',
          'Copy brief, section map, bump, and upsell ideas for each',
        ],
        acceptLabel: 'Yes — add all ten blueprints for $39',
        declineLabel: 'No thanks — I’ll start with my own offer',
        deliverySubject: 'Your Ten-Funnel Blueprint Pack',
        deliveryBody:
          'Your ten funnel briefs, section maps, and offer-mechanic ideas are ready at the link below.',
        accessUrl: 'https://example.com/replace-with-your-access-link',
        ordinal: 0,
      },
      {
        key: 'agency-toolkit',
        productKey: 'owned-funnel-agency-toolkit',
        name: 'Client Funnel Delivery Toolkit',
        stepLabel: 'Upgrade 2 of 2',
        eyebrow: 'Turn the builder into a repeatable client service',
        title: 'Want the client intake and handoff system',
        accent: 'already built?',
        description:
          'Use a clear workflow for collecting an offer, getting approvals, duplicating the funnel, handing over accounts, and proving what went live.',
        price: '$79',
        regularPrice: '$199',
        priceAmount: 79,
        currency: 'USD',
        items: [
          'Client offer-intake questionnaire',
          'Copy and claims approval checklist',
          'Account and credential handoff guide',
          'Funnel duplication workflow',
          'Launch receipt and QA report template',
          'Maintenance and change-request playbook',
        ],
        acceptLabel: 'Yes — add the Client Delivery Toolkit for $79',
        declineLabel: 'No thanks — I’m building only for myself',
        deliverySubject: 'Your Client Funnel Delivery Toolkit',
        deliveryBody:
          'Your client intake, approval, handoff, launch, and maintenance toolkit is ready at the link below.',
        accessUrl: 'https://example.com/replace-with-your-access-link',
        ordinal: 1,
      },
    ],
    completion: {
      title: 'You own the builder now. Everything is attached to your email.',
      description:
        'Your receipt, source access, quickstart, and every purchased add-on will arrive at the email used at checkout.',
      backLabel: 'Back to Owned Funnel Builder',
    },
  },
  {
    offerSlug: 'vibe-code-anything',
    supportEmail: 'support@example.com',
    base: {
      productKey: 'vibe-code-anything',
      name: 'Maestro SaaS UI Template',
      priceAmount: 29,
      currency: 'USD',
      deliverySubject: 'Your Maestro SaaS UI Template access',
      deliveryBody:
        'Thanks for your purchase. Your access instructions are ready at the link below.',
      accessUrl: 'https://example.com/replace-with-your-access-link',
    },
    bump: {
      key: 'prompt-pack',
      productKey: 'vibe-code-prompt-pack',
      name: 'Vibe Coding Prompt Pack',
      priceAmount: 19,
      currency: 'USD',
      deliverySubject: 'Your Vibe Coding Prompt Pack',
      deliveryBody: 'Your prompt pack is ready at the link below.',
      accessUrl: 'https://example.com/replace-with-your-access-link',
    },
    upsells: [
      {
        key: 'blueprints',
        productKey: 'vibe-code-five-app-blueprints',
        name: 'Five-App Blueprint Pack',
        stepLabel: 'Upgrade 1 of 2',
        eyebrow: 'Five complete starting points',
        title: 'Want five apps',
        accent: 'already mapped for Maestro?',
        description:
          'Skip the product-planning blank page too. Each blueprint tells your coding agent exactly what to build, where it belongs, and how to prove it works.',
        price: '$39',
        regularPrice: '$99',
        priceAmount: 39,
        currency: 'USD',
        items: [
          'Client portal blueprint',
          'Launch tracker blueprint',
          'AI research workspace',
          'Approval and operations app',
          'Vertical SaaS starter',
          'PRD, schema, screens, prompts, and gates',
        ],
        acceptLabel: 'Yes — add all five blueprints for $39',
        declineLabel: 'No thanks — I’ll start with my own idea',
        deliverySubject: 'Your Five-App Blueprint Pack',
        deliveryBody: 'Your five app blueprints are ready at the link below.',
        accessUrl: 'https://example.com/replace-with-your-access-link',
        ordinal: 0,
      },
      {
        key: 'launch',
        productKey: 'vibe-code-production-launch-pack',
        name: 'Production Launch Pack',
        stepLabel: 'Upgrade 2 of 2',
        eyebrow: 'The production provider playbook',
        title: 'Want the boring production services',
        accent: 'mapped out too?',
        description:
          'Give your coding agent reviewed implementation paths for the services every serious app eventually needs—without pretending your real credentials are already connected.',
        price: '$79',
        regularPrice: '$199',
        priceAmount: 79,
        currency: 'USD',
        items: [
          'Auth provider setup recipes',
          'Dodo billing implementation',
          'Transactional email wiring',
          'Analytics and error monitoring',
          'Storage and deployment checklist',
          'Launch gates and rollback proof',
        ],
        acceptLabel: 'Yes — add the Production Launch Pack for $79',
        declineLabel: 'No thanks — I’ll wire the production services myself',
        deliverySubject: 'Your Production Launch Pack',
        deliveryBody: 'Your production launch pack is ready at the link below.',
        accessUrl: 'https://example.com/replace-with-your-access-link',
        ordinal: 1,
      },
    ],
    completion: {
      title: 'You’re in. Everything is attached to your email.',
      description:
        'Your receipt and access instructions will arrive at the email used at checkout.',
      backLabel: 'Back to Vibe Code Anything',
    },
  },
] as const;

export type FunnelDefinition = (typeof FUNNELS)[number];
export type FunnelUpsell = FunnelDefinition['upsells'][number];

export function getFunnelDefinition(offerSlug: string): FunnelDefinition | undefined {
  return FUNNELS.find((funnel) => funnel.offerSlug === offerSlug);
}

export function getProductDefinition(productKey: string) {
  for (const funnel of FUNNELS) {
    if (funnel.base.productKey === productKey) return { funnel, product: funnel.base };
    if (funnel.bump?.productKey === productKey) return { funnel, product: funnel.bump };
    const upsell = funnel.upsells.find((step) => step.productKey === productKey);
    if (upsell) return { funnel, product: upsell };
  }
  return undefined;
}
